export enum MessagingCodes{
    ADD_USER,
    UPDATE_USER,
    DELETE_USER,
    GET_USER,
    GET_USERS,
    GET_MANY_RESPONSE,
    GET_RESPONSE,
    ADD_RESPONSE,
    UPDATE_RESPONSE,
    DELETE_RESPONSE
}